import type { Car } from "./types";

export const cars: Car[] = [
  {
    id: "1",
    slug: "golf-gti",
    name: "Volkswagen Golf GTI",
    model: "Golf GTI",
    bodyType: "Hatchback",
    year: 2024,
    price: 32000,
    color: "Reflex Silver",
    colorHex: "#C0C5C9",
    horsepower: 245,
    topSpeed: 250,
    zeroToHundred: 6.2,
    range: 720,
    fuel: "Petrol",
    transmission: "DSG",
    seats: 5,
    description:
      "The original hot hatch. The Golf GTI blends everyday usability with sharp, responsive performance and the iconic tartan interior.",
    features: ["Adaptive Chassis Control", "Digital Cockpit Pro", "Sport Seats", "IQ.LIGHT LED", "Travel Assist"],
    badge: "Icon",
    rating: 4.8,
    inStock: true,
    image: "/cars/golf-gti.jpg",
  },
  {
    id: "2",
    slug: "passat-r-line",
    name: "Volkswagen Passat R-Line",
    model: "Passat R-Line",
    bodyType: "Sedan",
    year: 2024,
    price: 38000,
    color: "Deep Black",
    colorHex: "#0E0E10",
    horsepower: 204,
    topSpeed: 240,
    zeroToHundred: 7.1,
    range: 850,
    fuel: "Diesel",
    transmission: "DSG",
    seats: 5,
    description:
      "Refined business class. The Passat R-Line delivers executive comfort with sporty R-Line styling and effortless long-distance cruising.",
    features: ["R-Line Body Kit", "ErgoActive Seats", "Dynaudio Sound", "Matrix LED", "Trailer Assist"],
    rating: 4.6,
    inStock: true,
    image: "/cars/passat.jpg",
  },
  {
    id: "3",
    slug: "tiguan-r",
    name: "Volkswagen Tiguan R",
    model: "Tiguan R",
    bodyType: "SUV",
    year: 2024,
    price: 52000,
    color: "Lapiz Blue",
    colorHex: "#0F3D5E",
    horsepower: 320,
    topSpeed: 250,
    zeroToHundred: 5.1,
    range: 620,
    fuel: "Petrol",
    transmission: "DSG",
    seats: 5,
    description:
      "The performance SUV. Tiguan R brings track-bred power to the family SUV with 4MOTION all-wheel drive and R-tuned suspension.",
    features: ["4MOTION AWD", "R-Performance Torque Vectoring", "Akrapovic Exhaust", "DCC Adaptive Suspension", "Sport Plus Mode"],
    badge: "Performance",
    rating: 4.9,
    inStock: true,
    image: "/cars/tiguan-r.jpg",
  },
  {
    id: "4",
    slug: "id4-pro",
    name: "Volkswagen ID.4 Pro",
    model: "ID.4 Pro",
    bodyType: "EV",
    year: 2024,
    price: 45000,
    color: "Moonlight Grey",
    colorHex: "#5A5F66",
    horsepower: 286,
    topSpeed: 180,
    zeroToHundred: 6.7,
    range: 546,
    fuel: "Electric",
    transmission: "Automatic",
    seats: 5,
    description:
      "Electric, spacious, intuitive. The ID.4 Pro is the all-electric family SUV with a long-range battery and instant torque.",
    features: ["77 kWh Battery", "Fast Charging 175 kW", "ID.Light System", "Augmented Reality HUD", "Travel Assist Plus"],
    badge: "Electric",
    rating: 4.7,
    inStock: true,
    image: "/cars/id4-pro.jpg",
  },
  {
    id: "5",
    slug: "arteon-shooting-brake",
    name: "Volkswagen Arteon Shooting Brake",
    model: "Arteon SB",
    bodyType: "Estate",
    year: 2024,
    price: 49000,
    color: "Energetic Orange",
    colorHex: "#D24A1F",
    horsepower: 280,
    topSpeed: 250,
    zeroToHundred: 5.7,
    range: 780,
    fuel: "Petrol",
    transmission: "DSG",
    seats: 5,
    description:
      "Gran Turismo meets estate practicality. The Arteon Shooting Brake combines a sweeping coupe roofline with a generous load area.",
    features: ["Frameless Doors", "Panoramic Roof", "Harman Kardon Audio", "IQ.LIGHT LED Matrix", "Area View Camera"],
    rating: 4.5,
    inStock: true,
    image: "/cars/arteon.jpg",
  },
  {
    id: "6",
    slug: "polo-gti",
    name: "Volkswagen Polo GTI",
    model: "Polo GTI",
    bodyType: "Hatchback",
    year: 2024,
    price: 28000,
    color: "Pure White",
    colorHex: "#F4F4F4",
    horsepower: 207,
    topSpeed: 240,
    zeroToHundred: 6.5,
    range: 680,
    fuel: "Petrol",
    transmission: "DSG",
    seats: 5,
    description:
      "Compact, punchy, and unmistakably GTI. The Polo GTI is the city-friendly hot hatch with serious performance credentials.",
    features: ["Sport Plus Mode", "Beats Audio", "Digital Cockpit", "Sport Steering Wheel", "Front Assist"],
    badge: "Hot Hatch",
    rating: 4.6,
    inStock: true,
    image: "/cars/polo-gti.jpg",
  },
  {
    id: "7",
    slug: "touareg-e-hybrid",
    name: "Volkswagen Touareg eHybrid",
    model: "Touareg eHybrid",
    bodyType: "SUV",
    year: 2024,
    price: 68000,
    color: "Galvanic Grey",
    colorHex: "#6B7077",
    horsepower: 462,
    topSpeed: 240,
    zeroToHundred: 4.9,
    range: 900,
    fuel: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    description:
      "Flagship luxury hybrid SUV. The Touareg eHybrid pairs a powerful V6 with electric drive for silent city runs and effortless touring.",
    features: ["Plug-in Hybrid", "Air Suspension", "Innovision Cockpit", "Night Vision", "4-Corner Air Suspension"],
    badge: "Flagship",
    rating: 4.8,
    inStock: false,
    image: "/cars/touareg.jpg",
  },
  {
    id: "8",
    slug: "id-buzz",
    name: "Volkswagen ID. Buzz",
    model: "ID. Buzz",
    bodyType: "EV",
    year: 2024,
    price: 58000,
    color: "Candy White / Energetic Orange",
    colorHex: "#F4F4F4",
    horsepower: 286,
    topSpeed: 160,
    zeroToHundred: 7.9,
    range: 420,
    fuel: "Electric",
    transmission: "Automatic",
    seats: 5,
    description:
      "The legend reborn, electric. The ID. Buzz reimagines the iconic Microbus for the electric age with retro charm and modern tech.",
    features: ["77 kWh Battery", "Retro-Modern Design", "ID.Light", "Panoramic Roof", "Travel Assist"],
    badge: "Icon",
    rating: 4.9,
    inStock: true,
    image: "/cars/id-buzz.jpg",
  },
];

export function getCarBySlug(slug: string): Car | undefined {
  return cars.find((c) => c.slug === slug);
}

export function getFeaturedCars(): Car[] {
  return cars.filter((c) => c.badge).slice(0, 4);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(price);
}
